### ISSUE TITLE
体验障碍

### ISSUE THREAD

**Issue by siyuanlau** [viosey/O#1]
1.动画效果太过生硬，如右上角天气处和点按“编辑”按钮处；
2.有某些地方字体大小与其他地方不同(如“编辑”按钮字体过小）；
3.天气栏打开只能按城市名或气温，可否把右边那三角形也动用一下？
测试浏览器：Chrome 55.0.2883.87 (64-bit) (Ubuntu16.04)

**Comment by viosey** [comment]
1. 桌面端动画生硬是因为桌面端有一些其他的动画会影响视觉效果
2. 编辑字体小是为了不干扰视觉
3. 因为三角形没有和「城市名、气温」在同一个 div 中，所以按钮现在是只能点击「城市名、期望」
