### ISSUE TITLE
挑挑毛病刷波存在感

### ISSUE THREAD

**Issue by EYHN** [viosey/O#2]
水波纹在安卓chrome卡出翔
居然可以添加空的todo
搜索框添加md的卡片效果
天气能不能加点特效，加点图标会更有可读性。
更多css过渡 和 md特效！

**Comment by thomas0612** [comment]
@EYHN 楼上大佬，这个面板在什么环境下才可以运行？求指点

**Comment by EYHN** [comment]
@thomas0612  额 大佬 开发者有链接 https://o.viosey.com
如果想自己运行的话 应该需要node环境

**Comment by iblh** [comment]
滑稽原来是你
